const AUTH = {
  UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  JWT_MISSING: 'AUTH.JWT_MISSING',
  INVALID_ACCESS: 'AUTH.INVALID_ACCESS',
  ALREADY_EXISTS: 'AUTH.ALREADY_EXISTS',
};

const USER = {
  EMAIL_OR_PHONE_USED: 'USER.EMAIL_OR_PHONE_USED',
};

const PERMISSION = {
  NAME_USED: 'PERMISSION.NAME_USED',
  FORBIDDEN: 'PERMISSION.FORBIDDEN',
};

const ERRORS = {
  AUTH,
  USER,
  PERMISSION,
};

export default ERRORS;
